# Generated by Django 4.1.1 on 2022-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='service_completed',
            field=models.BooleanField(default=False),
        ),
    ]
