name: CI
on:
  push:
    branches:
      - develop
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
          architecture: 'x64'
      - name: Install requirements
        run: pip install requirements.txt
      - name: Check codestyle
        run: pycodestyle ./api_massage/*.py
      - name: Tests
        run: python manage.py test
  build_and_pub:
    needs: [run_tests]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN}}
      NAME: ${{ secrets.DOCKER_NAME}}
    steps:
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_TOKEN}} | docker login -u ${{ secrets.DOCKER_LOGIN}} --password-stdin
      - uses: actions/checkout@develop
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile
      - name: Push image to docker
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
