name: CI
on:
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
          architecture: 'x64'
      - name: Install requirements
        run: pip install requirements.txt
      - name: Check codestyle
        run: pycodestyle ./api_massage/*.py
      - name: Tests
        run: python manage.py test